variable "prefix" {}
variable "env" {}
variable "region" {}
variable "vpc_cidr_block" {}
variable "private_subnet_count" {}
variable "ecs_service_desired_count" {}
variable "image" {}
variable "build_number" {}
variable "ecr_crm_image_version" {}
variable "fargate_container_memory" {}
variable "fargate_container_cpu" {}
variable "app_port" {}
variable "admin_workstation_ip" {}
variable "database_name" {}
variable "database_user" {}
variable "database_password" {}
variable "database_password_arn" {}
variable "database_port" {}
variable "color" {}